# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2e5f175ea82dd5b3e8b658de2ff1222745c3aa49bd64c8725be0d6cf4f44730f2c7874b80dfec670020520fe2a6627ee4e3cbc2e63b97a1071b88c8a2933c6e

test:
  secret_key_base: d0673fc652fc8b82393ebcf739d0585feeb60d8089ae38cdbfadc404bfcbd270a2c97e96ac27e49500033aad29c007856a30e13fe479266367791e9f7c475f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
